package StaffMedico;

import Conexion.TestDBConnectionPool;
import Conexion.TestDBConnectionPool;
import InicioSesion.inicioRecepcionista;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.rmi.Remote;
import java.rmi.server.UnicastRemoteObject;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jeanpiere Palacios Barrutia
 */
public class Especialistas extends javax.swing.JFrame{
    
    TestDBConnectionPool conE = new TestDBConnectionPool();
    Connection conetE;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int idE;
    private TableRowSorter trsfiltro;
    String filtro;
    
    public Especialistas() throws RemoteException {
        initComponents();
        setLocationRelativeTo(null);
        metodoListarEspecialistas();
    }
    
    public void metodoListarEspecialistas() throws RemoteException{
        String sql ="SELECT medico.id_dni_personal, personal.apellido_paterno, personal.apellido_materno, personal.nombres, especialidad.nombre_especialidad, personal.fecha_nacimiento, turno.descripcion, COUNT(citas.dni_medico) AS 'CONSULTAS' FROM medico\n" +
        "INNER JOIN personal ON personal.id_dni = medico.id_dni_personal\n" +
        "INNER JOIN especialidad ON medico.codigo_especialidad = especialidad.codigo_especialidad\n" +
        "INNER JOIN turno ON personal.turno = turno.codigo_turno\n" +
        "INNER JOIN citas ON medico.id_dni_personal = citas.dni_medico AND citas.dni_medico = personal.id_dni\n" +
        "GROUP BY id_dni_personal";
        
        try{
            conetE = conE.test();
            st = conetE.createStatement();
            rs = st.executeQuery(sql);
            Object[] especialistas = new Object[8];
            modelo = (DefaultTableModel) TableEspecialidad.getModel();
            
            while(rs.next()){
                especialistas [0] = rs.getInt("id_dni_personal");
                especialistas [1] = rs.getString("apellido_paterno");
                especialistas [2] = rs.getString("apellido_materno");
                especialistas [3] = rs.getString("nombres");
                especialistas [4] = rs.getString("nombre_especialidad");
                especialistas [5] = rs.getString("fecha_nacimiento");
                especialistas [6] = rs.getString("descripcion");
                especialistas [7] = rs.getInt("CONSULTAS");
                
                modelo.addRow(especialistas);
            }
            TableEspecialidad.setModel(modelo);
        }catch(Exception e){
            
        }
    }
    
    public void buscarEspecialista(String buscar){
        TableEspecialidad.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundAsistencia = new javax.swing.JPanel();
        Especialista_Title = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        botonRegresar_Especialistas = new javax.swing.JButton();
        dniBuscadorLabel_Especialistas = new javax.swing.JLabel();
        lista_Especialistas = new javax.swing.JLabel();
        TxtFieldEspecialista = new javax.swing.JTextField();
        dniBuscadorTxtField_Especialistas2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEspecialidad = new javax.swing.JTable();
        btn_buscarEspecialista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundAsistencia.setBackground(new java.awt.Color(255, 255, 255));
        backgroundAsistencia.setMinimumSize(new java.awt.Dimension(1280, 431));
        backgroundAsistencia.setPreferredSize(new java.awt.Dimension(1280, 645));
        backgroundAsistencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Especialista_Title.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Especialista_Title.setText("ESPECIALISTAS");
        backgroundAsistencia.add(Especialista_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jSeparator8.setBackground(new java.awt.Color(217, 217, 217));
        jSeparator8.setForeground(new java.awt.Color(217, 217, 217));
        jSeparator8.setPreferredSize(new java.awt.Dimension(1280, 0));
        backgroundAsistencia.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 1280, 20));

        botonRegresar_Especialistas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegresar_Especialistas.setForeground(new java.awt.Color(41, 98, 255));
        botonRegresar_Especialistas.setText("< REGRESAR");
        botonRegresar_Especialistas.setBorder(null);
        botonRegresar_Especialistas.setBorderPainted(false);
        botonRegresar_Especialistas.setContentAreaFilled(false);
        botonRegresar_Especialistas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar_Especialistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresar_EspecialistasMouseClicked(evt);
            }
        });
        botonRegresar_Especialistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresar_EspecialistasActionPerformed(evt);
            }
        });
        backgroundAsistencia.add(botonRegresar_Especialistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, 30));

        dniBuscadorLabel_Especialistas.setText("Buscar Especialista");
        backgroundAsistencia.add(dniBuscadorLabel_Especialistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        lista_Especialistas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lista_Especialistas.setText("LISTA DE ESPECIALISTAS");
        backgroundAsistencia.add(lista_Especialistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 242, -1, -1));

        TxtFieldEspecialista.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        TxtFieldEspecialista.setPreferredSize(new java.awt.Dimension(284, 35));
        TxtFieldEspecialista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldEspecialistaActionPerformed(evt);
            }
        });
        TxtFieldEspecialista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtFieldEspecialistaKeyTyped(evt);
            }
        });
        backgroundAsistencia.add(TxtFieldEspecialista, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        dniBuscadorTxtField_Especialistas2.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniBuscadorTxtField_Especialistas2.setPreferredSize(new java.awt.Dimension(284, 35));
        dniBuscadorTxtField_Especialistas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniBuscadorTxtField_Especialistas2ActionPerformed(evt);
            }
        });
        backgroundAsistencia.add(dniBuscadorTxtField_Especialistas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        TableEspecialidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "APELLIDO PATERNO", "APELLIDO MATERNO", "NOMBRES", "ESPECIALIDAD", "FECHA", "TURNO", "CONSULTAS"
            }
        ));
        jScrollPane1.setViewportView(TableEspecialidad);

        backgroundAsistencia.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 1060, 340));

        btn_buscarEspecialista.setBackground(new java.awt.Color(204, 255, 255));
        btn_buscarEspecialista.setText("BUSCAR");
        btn_buscarEspecialista.setBorder(null);
        btn_buscarEspecialista.setPreferredSize(new java.awt.Dimension(136, 31));
        btn_buscarEspecialista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarEspecialistaActionPerformed(evt);
            }
        });
        backgroundAsistencia.add(btn_buscarEspecialista, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backgroundAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backgroundAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresar_EspecialistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresar_EspecialistasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonRegresar_EspecialistasActionPerformed

    private void TxtFieldEspecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldEspecialistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldEspecialistaActionPerformed

    private void dniBuscadorTxtField_Especialistas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniBuscadorTxtField_Especialistas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniBuscadorTxtField_Especialistas2ActionPerformed

    public void buscar(String buscar) throws RemoteException{
        Buscar p = new Buscar();
        System.out.println("Estableciendo comunicación con el método");
        DefaultTableModel modelo = p.Especialistas(buscar);
        TableEspecialidad.setModel(modelo);
    }   
    
    private void btn_buscarEspecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarEspecialistaActionPerformed
        try {
            // TODO add your handling code here:
            buscar(TxtFieldEspecialista.getText());
            System.out.println("Comunicación exitosa, consulta concluida");
        } catch (RemoteException ex) {
            Logger.getLogger(Especialistas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_buscarEspecialistaActionPerformed

    private void TxtFieldEspecialistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFieldEspecialistaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldEspecialistaKeyTyped

    private void botonRegresar_EspecialistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresar_EspecialistasMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new inicioRecepcionista().setVisible(true);
    }//GEN-LAST:event_botonRegresar_EspecialistasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Especialistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Especialistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Especialistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Especialistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Especialistas().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(Especialistas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Especialista_Title;
    private javax.swing.JTable TableEspecialidad;
    private javax.swing.JTextField TxtFieldEspecialista;
    private javax.swing.JPanel backgroundAsistencia;
    private javax.swing.JButton botonRegresar_Especialistas;
    private javax.swing.JButton btn_buscarEspecialista;
    private javax.swing.JLabel dniBuscadorLabel_Especialistas;
    private javax.swing.JTextField dniBuscadorTxtField_Especialistas2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lista_Especialistas;
    // End of variables declaration//GEN-END:variables
}
